/**
 * Content for the dedicated OyeChats vs Zoho SalesIQ page.
 *
 * SOURCE OF TRUTH: `oye-chats-platform/docs/competitive/oyechats-vs-zoho-salesiq.md`.
 * Every claim below is derived from that document and carries its evidence tier.
 * Do not add, sharpen or "improve" a claim here without changing the doc first —
 * if the two disagree, the doc wins and this file is wrong.
 *
 * Three rules this file exists to enforce, restated because they are the ones
 * most likely to be broken by a well-meaning edit (posture updated 2026-08-31):
 *
 *  1. Zoho pricing is DATED and CAVEATED. Their pricing *model* plus
 *     representative figures are allowed, but every figure ships next to an
 *     "as of <month year>, verify" line, because rival prices move without
 *     notice. Our own numbers are read live from `@/lib/pricing`.
 *  2. NO invented benchmarks, conversion rates, ROI figures or "Nx better"
 *     claims, and NO manufactured head-to-head score. A qualitative, dated
 *     account of a real hands-on test is allowed; a number like "85 vs 34.5"
 *     is not.
 *  3. The honest losses stay in. SalesIQ wins on headline price, on ecosystem
 *     breadth, on omnichannel and voice, on India data residency, and on native
 *     Zoho CRM wiring, and this page says so. A grid where we win every row is
 *     not read as a strong product, it is read as marketing.
 *
 * "Zoho" and "Zoho SalesIQ" are trademarks of Zoho Corporation, used here
 * nominatively to identify the product compared. No affiliation or endorsement
 * is implied, which is also why this page uses a letter monogram rather than
 * their logo.
 */

export const ZOHO_SLUG = 'oyechats-vs-zoho-salesiq';
export const ZOHO_PATH = `/compare/${ZOHO_SLUG}`;

/** The sentence the whole page hangs on. */
export const THESIS =
  'Zoho SalesIQ is live chat that has added AI. OyeChats is an AI agent that has added live chat.';

export const META_TITLE = 'OyeChats vs Zoho SalesIQ: A Full Comparison';
export const META_DESCRIPTION =
  'OyeChats vs Zoho SalesIQ, compared honestly: grounded AI answers, BANT and MEDDIC qualification, live handoff, pricing shape, and when SalesIQ wins.';

/** The up-front decision box. Answer engines quote this; humans skim it. */
export type Verdict = { heading: string; lead: string; points: string[] };

export const CHOOSE_OYE: Verdict = {
  heading: 'Choose OyeChats if',
  lead: 'You are not already standardised on Zoho, and what you want out of chat is qualified pipeline rather than a staffed inbox.',
  points: [
    'You want an AI agent answering from your own content on day one, not a bot-building project',
    'You want every conversation scored on BANT, MEDDIC, CHAMP or GPCTBA+C&I before a rep sees it',
    'Your CRM is HubSpot, Salesforce, Pipedrive, Zoho or a spreadsheet, and you want leads pushed to any of them',
    'You would rather your bill track conversation volume than how many people log in',
  ],
};

export const CHOOSE_ZOHO: Verdict = {
  heading: 'Choose Zoho SalesIQ if',
  lead: 'You already run on Zoho. This is not a courtesy line: for a business inside that suite, SalesIQ is usually the right call.',
  points: [
    'Your CRM is Zoho CRM and your helpdesk is Zoho Desk, and you want chat wired natively into both',
    'You need to meet customers on WhatsApp, Instagram and other channels, or take audio and video calls',
    'You want a mature human live chat product first, with the AI layer as something you configure over time',
    'Indian data residency inside a suite you already trust is a requirement rather than a preference',
    'You are buying the wider Zoho suite anyway, where the marginal cost of adding chat is small',
  ],
};

/** "What each product actually is" — the two positioning cards. */
export const WHAT_THEY_ARE = {
  oye: {
    name: 'OyeChats',
    category: 'AI agent with live chat',
    body: 'You point OyeChats at your own content (your site, your PDFs, your docs) and it builds a private knowledge base. The widget goes live with one script tag. Answers are generated by retrieval over that content, every conversation is silently scored for sales-readiness in the background, and a human on your team can take over the same thread at any moment.',
  },
  zoho: {
    name: 'Zoho SalesIQ',
    category: 'Live chat with a bot builder',
    body: 'SalesIQ is a live chat, visitor-tracking and engagement product inside the Zoho suite. Its centre of gravity is human live chat plus visitor intelligence, with the Zobot builder on every tier and its Answer Bot and Zia AI layer on Enterprise. Its defining strength is native integration with Zoho CRM, Zoho Desk and the rest of the ecosystem.',
  },
} as const;

/**
 * The long-form deep dives. `edge` mirrors the shared matrix in `@/lib/compare`
 * and is judged from our side, but marks `tie` and `them` honestly.
 */
/** Which figure renders beside a dive. Keys map to `./visuals.tsx`. */
export type DiveVisual = 'answers' | 'qualification' | 'handoff' | 'webhooks' | 'install';

export type DeepDive = {
  id: string;
  eyebrow: string;
  heading: string;
  edge: 'oye' | 'them' | 'tie';
  oye: string;
  zoho: string;
  /** The fair reading. Written to survive a sceptical reader, not to win. */
  verdict: string;
  visual: DiveVisual;
  /** Caption under the figure. Says what is being shown, not what to think. */
  visualCaption: string;
};

export const DEEP_DIVES: DeepDive[] = [
  {
    id: 'answers',
    eyebrow: 'Grounded answers',
    heading: 'Retrieval over your content vs a bot you build',
    edge: 'oye',
    oye: 'OyeChats runs hybrid retrieval: semantic vector search over your content combined with Postgres full-text keyword search, so an exact product name matches as reliably as a vaguely-phrased question. Content comes from a crawl of your live site or from PDF, DOCX and TXT uploads. A relevance gate, on by default, lets the agent decline rather than improvise when nothing relevant comes back.',
    zoho: 'SalesIQ has real AI: the Zobot flow builder on every tier, and on the Enterprise tier the Answer Bot plus the Zia Agents launched in 2026, which retrieve from your knowledge-base articles and uploaded documents and can bring your own LLM. It is capable, and two things are true of it: the AI answering layer sits on the top tier, and it grounds on a knowledge base you assemble rather than a one-step crawl of your site.',
    verdict:
      'Not whether grounded answers are possible on both. They are. It is what a new account does on day one and where the AI sits in the price list. Ours crawls your own site and answers from it from the entry tier; theirs is a build on knowledge-base content, on Enterprise. In a hands-on test in July 2026, given the same website content, OyeChats answered from the pages while SalesIQ’s out-of-box bot either declined or, allowed to use built-in knowledge, invented a price.',
    visual: 'answers',
    visualCaption:
      'A crawl of your site, then a grounded answer. Sources stay internal, not shown to the visitor.'
  },
  {
    id: 'qualification',
    eyebrow: 'Lead qualification',
    heading: 'Sales frameworks, not just engagement scores',
    edge: 'oye',
    oye: 'Pick a framework per agent: BANT, MEDDIC, CHAMP or GPCTBA+C&I. Weighted dimensions produce a composite score out of 100 that maps to a tier: MQL at 30, SAL at 55, SQL at 75. Extraction runs after the answer has already streamed to the visitor, so it never adds latency, and it infers signals from ordinary conversation rather than interrogating. Every signal is written to an append-only audit trail, and a score never downgrades. Crossing into SQL fires an email and a webhook.',
    zoho: 'SalesIQ has visitor scoring and lead ranking built around engagement and on-site behaviour, fed by genuinely strong visitor tracking. What it does not present as a configurable product primitive is a named B2B sales framework.',
    verdict:
      'This is the widest gap on the page, and it is a difference in the question being answered. Behavioural scoring tells you who is engaged. Framework qualification tells you who is ready to buy, and which dimension they are still weak on.',
    visual: 'qualification',
    visualCaption:
      'One conversation scored, and the tier that score lands on.'
  },
  {
    id: 'handoff',
    eyebrow: 'Human handoff',
    heading: 'Both do live chat well',
    edge: 'tie',
    oye: 'Handoff runs on an explicit state machine (bot, waiting, live, closed) with enforced transitions rather than ad-hoc flags. Operator routing, departments, canned shortcut replies, offline message capture, an immutable audit log, and WebSocket delivery. The operator inherits the full transcript and the qualification score.',
    zoho: 'Live chat is what SalesIQ is for, and it is mature: routing, departments, canned replies, operator mobile apps, and richer in-chat modalities than we offer today.',
    verdict:
      'We are not going to claim we out-live-chat a dedicated live chat vendor. Call it a tie. Our narrow advantage is a consequence of the row above: the operator picking up a handoff already knows the tier of the lead before they type a word.',
    visual: 'handoff',
    visualCaption:
      'The four session states, and what an operator picks up with.'
  },
  {
    id: 'integrations',
    eyebrow: 'Integrations',
    heading: 'CRM-agnostic, with an honest gap',
    edge: 'oye',
    oye: 'Every event (a lead captured, a tier crossed, a handoff, a booking) is delivered as an HMAC-signed outbound webhook, with five delivery attempts backing off 30 seconds, 2 minutes, 10 minutes and an hour if your endpoint is down. Install is documented for HTML, Next.js, React, Vue, Angular, Shopify, Squarespace, Svelte, Webflow, Wix, WordPress, Framer, Bubble, Astro and GTM.',
    zoho: 'Native, first-party, deeply-wired integration with Zoho CRM, Zoho Desk and the wider suite. It is the kind of integration only the vendor who owns both sides can build.',
    verdict:
      'Stated plainly: OyeChats has no native Zoho CRM integration. Leads reach any CRM through HMAC-signed webhooks. That is genuinely CRM-agnostic, and it is genuinely more work than a first-party connector. If your CRM is Zoho, that is a real point for them.',
    visual: 'webhooks',
    visualCaption:
      'Where a qualified lead goes, and the retry ladder behind it.'
  },
  {
    id: 'setup',
    eyebrow: 'Time to live',
    heading: 'One script tag',
    edge: 'oye',
    oye: 'Add your content, copy the snippet, paste it before the closing body tag. The file your visitors download is about 3KB gzipped; the chat app itself only loads when someone actually opens the widget. It mounts inside a shadow root, so the CSS of your site cannot break the widget and the widget cannot leak into your site.',
    zoho: 'A suite product carrying visitor tracking, routing rules, departments and a bot builder is configured before it is useful. That is the cost of its flexibility, not a defect.',
    verdict:
      'Setup depth, not vendor competence. If you want to be answering questions this afternoon, the shallower setup wins. If you want to model a 12-person support org, the deeper one earns its configuration.',
    visual: 'install',
    visualCaption:
      'The whole install. There is no second step.'
  },
];

/**
 * The qualification tier ladder. Same thresholds the qualification service
 * uses, shared across all four frameworks. Rendered as positions on a ladder
 * beside the qualification dive rather than repeated as prose.
 */
export const TIERS: { tier: string; at: number }[] = [
  { tier: 'MQL', at: 30 },
  { tier: 'SAL', at: 55 },
  { tier: 'SQL', at: 75 },
];

/**
 * Outbound webhook retry ladder, rendered beside the integrations dive. These
 * are the backoff gaps between five delivery attempts, verified against
 * `webhook_service.py` (`_RETRY_DELAYS = [30, 120, 600, 3600]`, `_MAX_RETRIES = 5`).
 * There is no 4h step; do not add one back.
 */
export const RETRY_LADDER = ['30s', '2m', '10m', '1h'];

/**
 * Section anchors for the sticky pill nav. The page is long by design, so it
 * gets the same scroll-spy treatment as /features rather than asking a buyer
 * to scroll past four sections to find the pricing they came for.
 */
export const SECTIONS: { id: string; label: string }[] = [
  { id: 'verdict', label: 'Short answer' },
  { id: 'matrix', label: 'At a glance' },
  { id: 'differences', label: 'Differences' },
  { id: 'frameworks', label: 'Qualification' },
  { id: 'pricing', label: 'Pricing' },
  { id: 'when-zoho', label: 'When Zoho wins' },
  { id: 'switching', label: 'Switching' },
  { id: 'faq', label: 'FAQ' },
];

/** The four frameworks, for the qualification deep-dive table. */
export const FRAMEWORKS: { name: string; dimensions: string }[] = [
  { name: 'BANT', dimensions: 'Budget · Authority · Need · Timeline' },
  { name: 'MEDDIC', dimensions: 'Metrics · Economic buyer · Decision criteria · Decision process · Identify pain · Champion' },
  { name: 'CHAMP', dimensions: 'Challenges · Authority · Money · Prioritisation' },
  { name: 'GPCTBA+C&I', dimensions: 'Goals · Plans · Challenges · Timeline · Budget · Authority · Consequences' },
];

/** What switching actually involves. Deliberately unglamorous and true. */
export const MIGRATION_STEPS: { title: string; body: string }[] = [
  {
    title: 'Run both at once',
    body: 'Nothing forces a cutover. Put OyeChats on a single high-traffic page, or on a staging site, while SalesIQ keeps serving the rest. Both are one script tag.',
  },
  {
    title: 'Point it at your content',
    body: 'Crawl your site, or upload the PDFs and docs your team already sends to prospects. This is the step that decides answer quality, and it is measured in minutes, not sprints.',
  },
  {
    title: 'Pick a qualification framework',
    body: 'BANT is the default and fits most SMB sales motions. Switch to MEDDIC, CHAMP or GPCTBA+C&I per agent if your team already sells that way.',
  },
  {
    title: 'Wire the webhook',
    body: 'Point the tier-transition webhook at your CRM or automation tool so a lead crossing into SQL lands where your reps already work. If that CRM is Zoho, this is the step where you are doing work SalesIQ would have done for you.',
  },
];

export const FAQS: { q: string; a: string }[] = [
  {
    q: 'What is the real difference between OyeChats and Zoho SalesIQ?',
    a: 'Zoho SalesIQ is live chat that has added AI; OyeChats is an AI agent that has added live chat. SalesIQ starts from human chat and visitor tracking, with the Zobot builder on every tier and its Answer Bot and Zia AI layer on Enterprise. OyeChats starts from an AI agent that answers from your own content and scores every conversation on a sales framework, with human handoff built in. Both products have both halves. The difference is which half is the default, and where the AI sits in the price list.',
  },
  {
    q: 'Is OyeChats a good Zoho SalesIQ alternative if I do not use Zoho?',
    a: 'That is the case it is strongest in. The biggest advantage SalesIQ has is native integration with Zoho CRM and Zoho Desk, and that advantage does not transfer if your CRM is something else. OyeChats is CRM-agnostic: qualified leads are pushed by HMAC-signed webhook to whatever you already use.',
  },
  {
    q: 'Does Zoho SalesIQ do BANT lead scoring?',
    a: 'SalesIQ scores and ranks visitors on engagement and on-site behaviour, which is genuinely useful for spotting who is active on your site. It does not present a named B2B sales framework as a configurable primitive. OyeChats ships four of them (BANT, MEDDIC, CHAMP and GPCTBA+C&I) with weighted dimensions, a composite score out of 100, and MQL, SAL and SQL tiers.',
  },
  {
    q: 'Does Zoho SalesIQ have AI, and is it any good?',
    a: 'Yes, and it is capable. SalesIQ has the Zobot flow builder on every tier, and on its Enterprise tier the Answer Bot plus the Zia Agents it launched in 2026, which retrieve from your knowledge-base articles and uploaded documents and can even bring your own LLM. Two things are worth knowing before you compare. That AI answering layer sits on the Enterprise tier, whereas grounded AI is included on OyeChats from the entry tier. And it grounds on a knowledge base you assemble rather than a one-step crawl of your live site. This is a genuine product, not a strawman, so the honest way to judge it is to run both on a real page for a week.',
  },
  {
    q: 'Did you actually test the two side by side?',
    a: 'We did, in July 2026: both bots were given the same OyeChats website content and asked the same questions on a live page. OyeChats answered from the pages, declined out-of-scope questions and still redirected usefully, while SalesIQ’s out-of-box bot either could not find an answer or, when allowed to use built-in model knowledge, invented a price. That test predates Zoho’s 2026 AI updates and reflects the out-of-box, non-Enterprise experience, so treat it as one dated data point, not a verdict. The reliable test is your own: put both on one of your pages and read the transcripts.',
  },
  {
    q: 'Which one has better live chat?',
    a: 'Honestly, it is close, and SalesIQ has been doing it longer with richer in-chat modalities. OyeChats covers what most teams need: an explicit handoff state machine, operator routing, departments, canned replies, offline capture and an audit log. Our specific advantage is not the chat itself but what the operator inherits: the transcript and the qualification score are already attached when they pick up.',
  },
  {
    q: 'Can I keep using Zoho CRM with OyeChats?',
    a: 'Yes, through HMAC-signed webhooks rather than a native connector. Being straight about it: OyeChats has no first-party Zoho CRM integration, so this is plumbing you or your developer set up once. If deep Zoho CRM wiring with zero setup is the deciding factor, SalesIQ is the better buy.',
  },
  {
    q: 'How long does it take to get OyeChats live?',
    a: 'Add your content and paste one script tag before the closing body tag of your site. It works on WordPress, Webflow, Shopify, Next.js, React, Framer and anything else that lets you add a script. The loader is about 3KB and the chat app only downloads when a visitor opens the widget, so a page that nobody chats on pays almost nothing.',
  },
  {
    q: 'How does OyeChats pricing compare to Zoho SalesIQ?',
    a: 'They are shaped differently, and on headline price for a small team SalesIQ is often the cheaper line item, especially if you already buy the Zoho suite. SalesIQ prices per operator, with representative figures around $10 to $25 per operator per month as of August 2026 (verify their current page, rival pricing moves). Two things reshape the comparison. Its AI answering, the Answer Bot and Zia layer, sits on the Enterprise tier, while OyeChats includes grounded AI from Free and Starter. And OyeChats prices in credits, one AI reply is one credit, with operator seats included on each plan, so our bill tracks conversation volume rather than headcount: adding a colleague who wants to watch the inbox does not re-price the product.',
  },
  {
    q: 'Is there a free plan?',
    a: 'Yes. OyeChats Free is free forever: one chatbot, 100 credits a month, grounded AI answers and the website widget, with no card required. Both products have a free entry point, so the honest advice is to run each on a real page for a week and compare the transcripts.',
  },
];
